post.index:
    path: /post
    controller: App\Controller\PostController::index

post.create:
    path: /post/create
    controller: App\Controller\PostController::create

post.edit:
    path: /post/update/{id}
    controller: App\Controller\PostController::edit

post.delete:
    path: /post/delete/{id}
    controller: App\Controller\PostController::delete

post.search:
    path: /post/search
    controller: App\Controller\PostController::search

post.pagination:
    path: /post/pagination
    controller: App\Controller\PostController::pagination

auth.register:
    path: /register
    controller: App\Controller\RegisterController::index

auth.login:
    path: /login
    controller: App\Controller\SecurityController::login

auth.logout:
    path: /logout
    controller: App\Controller\SecurityController::logout